cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}
    --ntasks={resources.nodes}
    --nodes={resources.nodes}
    --output=logs/{rule}/{jobid}.out
    --error=logs/{rule}/{jobid}.err
    --partition={resources.partition}
    --parsable

default-resources:
  - mem_mb=2000
  - time=240
  - partition=low2
  - threads=1
  - nodes=1

jobs: 100
latency-wait: 60
local-cores: 1
restart-times: 5
max-jobs-per-second: 100
max-status-checks-per-second: 20
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-prefix: /home/baumlerc/miniconda3
conda-frontend: mamba
cluster-status: ~/.config/snakemake/slurm/slurm-status.py
shadow-prefix: /group/ctbrowngrp/scratch/baumlerc/snakemake-slurm
cluster-cancel: scancel
cluster-cancel-nargs: 1000
