# This is the file path to the metadata file.
# In this case, the file is the full metadata
# output of the SRA Run Selector.

metadata_file_path: metadata/SraRunTable.txt

# The kmer size within the database (`sourmash sig fileinfo`)
k_size:
  - 21
  - 31
  - 51

# The amoutn to scale representative kmer set
scale:
  - 1000